<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rssheep"
 *
 * Auto generated by Extension Builder 2019-10-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'rssheep',
    'description' => 'Extension for sheep administration',
    'category' => 'plugin',
    'author' => 'Ronald Wopereis',
    'author_email' => 'woepwoep@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '19.11.06',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
            'femanager' => '5.1.0-5.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
